metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.period: 5s
  reload.enabled: trueprocessors:
- add_docker_metadata: ~monitoring.enabled: true
setup.ilm.enabled: falseoutput.elasticsearch:
  hosts: ["elasticsearch:9200"]
  
logging.to_files: falsesetup:
  kibana.host: "kibana:5601"
  dashboards.enabled: true